name: Zola deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Zola
        run: |
          curl -sSL https://github.com/getzola/zola/releases/latest/download/zola-v0.21.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv zola /usr/local/bin/

      - name: Build site
        run: zola build
        working-directory: myblog

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: myblog/public
